#index:
#    path: /
#    controller: App\Controller\DefaultController::index
not_found:
  path: /404
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: '404.html.twig'